apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: castai-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: castai-agent
  name: castware-api-key
  namespace: castai-agent
data:
  API_KEY: "" #Insert your API key here