// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/castai/castware-operator/internal/castai (interfaces: CastAIClient)

// Package mock_castai is a generated GoMock package.
package mock_castai

import (
	context "context"
	reflect "reflect"

	castai "github.com/castai/castware-operator/internal/castai"
	gomock "github.com/golang/mock/gomock"
)

// MockCastAIClient is a mock of CastAIClient interface.
type MockCastAIClient struct {
	ctrl     *gomock.Controller
	recorder *MockCastAIClientMockRecorder
}

// MockCastAIClientMockRecorder is the mock recorder for MockCastAIClient.
type MockCastAIClientMockRecorder struct {
	mock *MockCastAIClient
}

// NewMockCastAIClient creates a new mock instance.
func NewMockCastAIClient(ctrl *gomock.Controller) *MockCastAIClient {
	mock := &MockCastAIClient{ctrl: ctrl}
	mock.recorder = &MockCastAIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCastAIClient) EXPECT() *MockCastAIClientMockRecorder {
	return m.recorder
}

// Me mocks base method.
func (m *MockCastAIClient) Me(arg0 context.Context) (*castai.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", arg0)
	ret0, _ := ret[0].(*castai.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockCastAIClientMockRecorder) Me(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockCastAIClient)(nil).Me), arg0)
}
