// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/castai/castware-operator/internal/castai/auth (interfaces: Auth)

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// ApiKey mocks base method.
func (m *MockAuth) ApiKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// ApiKey indicates an expected call of ApiKey.
func (mr *MockAuthMockRecorder) ApiKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiKey", reflect.TypeOf((*MockAuth)(nil).ApiKey))
}

// GetApiKey mocks base method.
func (m *MockAuth) GetApiKey(arg0 context.Context, arg1 client.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKey", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKey indicates an expected call of GetApiKey.
func (mr *MockAuthMockRecorder) GetApiKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKey", reflect.TypeOf((*MockAuth)(nil).GetApiKey), arg0, arg1)
}

// LoadApiKey mocks base method.
func (m *MockAuth) LoadApiKey(arg0 context.Context, arg1 client.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadApiKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadApiKey indicates an expected call of LoadApiKey.
func (mr *MockAuthMockRecorder) LoadApiKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadApiKey", reflect.TypeOf((*MockAuth)(nil).LoadApiKey), arg0, arg1)
}
