package bases

import "embed"

// Files contains the raw CRD manifests generated by controller-gen.
// These are embedded so the operator can install the CRDs at runtime.
//
//go:embed castware.cast.ai_clusters.yaml castware.cast.ai_components.yaml
var Files embed.FS

// Filenames enumerates the embedded CRD manifest files. The order matches the
// dependency chain (clusters before components).
var Filenames = []string{
	"castware.cast.ai_clusters.yaml",
	"castware.cast.ai_components.yaml",
}
